// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8o9vWu0l56kCoE3wDs0EuOvgWtp4EFI',
    appId: '1:740547853928:web:07f5e7b00a26de52f385dd',
    messagingSenderId: '740547853928',
    projectId: 'testmsdeveloper',
    authDomain: 'testmsdeveloper.firebaseapp.com',
    storageBucket: 'testmsdeveloper.appspot.com',
    measurementId: 'G-X2JLHXPRC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARqhPvkCeRnB5RBG-USAwoCDPunB2dL2k',
    appId: '1:740547853928:android:8dad711339ed624cf385dd',
    messagingSenderId: '740547853928',
    projectId: 'testmsdeveloper',
    storageBucket: 'testmsdeveloper.appspot.com',
  );
}
